KISSY.add(function(S,require,exports,module){
/*compiled by xtemplate#3.3.3*/
var ret = module.exports = function homeView(undefined){
var t;
var t0;
var t1;
var t2;
var t3;
var t4;
var t5;
var t6;
var t7;
var t8;
var t9;
var tpl = this;
var root = tpl.root;
var buffer = tpl.buffer;
var scope = tpl.scope;
var runtime = tpl.runtime;
var name = tpl.name;
var pos = tpl.pos;
var data = scope.data;
var affix = scope.affix;
var nativeCommands = root.nativeCommands;
var utils = root.utils;
var callFnUtil = utils["callFn"];
var callCommandUtil = utils["callCommand"];
var rangeCommand = nativeCommands["range"];
var foreachCommand = nativeCommands["foreach"];
var forinCommand = nativeCommands["forin"];
var eachCommand = nativeCommands["each"];
var withCommand = nativeCommands["with"];
var ifCommand = nativeCommands["if"];
var setCommand = nativeCommands["set"];
var includeCommand = nativeCommands["include"];
var parseCommand = nativeCommands["parse"];
var extendCommand = nativeCommands["extend"];
var blockCommand = nativeCommands["block"];
var macroCommand = nativeCommands["macro"];
var debuggerCommand = nativeCommands["debugger"];
function func7(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 17;
var id8 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
buffer = buffer.writeEscaped(id8);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 18;
var id9 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
buffer = buffer.writeEscaped(id9);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 19;
var exp11 = 'editStory/';
var id10 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp11 = ('editStory/')+(id10);
var callRet12
callRet12 = callFnUtil(tpl, scope, {escape:1,params:[exp11]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet12);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func0(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 7;
var exp2 = 'readStory/';
var id1 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp2 = ('readStory/')+(id1);
var callRet3
callRet3 = callFnUtil(tpl, scope, {escape:1,params:[exp2]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet3);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 9;
var id4 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"title"])));
buffer = buffer.writeEscaped(id4);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 13;
var id5 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"createTime"])));
buffer = buffer.writeEscaped(id5);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 14;
var id6 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"editTime"])));
buffer = buffer.writeEscaped(id6);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 16;
pos.line = 16;
var id13 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"account","id"])));
var exp15 = id13;
var id14 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp15 = (id13)===(id14);
buffer = ifCommand.call(tpl, scope, {params:[exp15],fn: func7}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 26;
var exp17 = 'readStory/';
var id16 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp17 = ('readStory/')+(id16);
var callRet18
callRet18 = callFnUtil(tpl, scope, {escape:1,params:[exp17]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet18);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 27;
var id19 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id19);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 29;
var id20 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"account","name"])));
buffer = buffer.writeEscaped(id20);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func29(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 47;
var id30 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
buffer = buffer.writeEscaped(id30);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 48;
var id31 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
buffer = buffer.writeEscaped(id31);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 49;
var exp33 = 'editStory/';
var id32 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp33 = ('editStory/')+(id32);
var callRet34
callRet34 = callFnUtil(tpl, scope, {escape:1,params:[exp33]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet34);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func22(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 37;
var exp24 = 'readStory/';
var id23 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp24 = ('readStory/')+(id23);
var callRet25
callRet25 = callFnUtil(tpl, scope, {escape:1,params:[exp24]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet25);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 39;
var id26 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"title"])));
buffer = buffer.writeEscaped(id26);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 43;
var id27 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"createTime"])));
buffer = buffer.writeEscaped(id27);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 44;
var id28 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"editTime"])));
buffer = buffer.writeEscaped(id28);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 46;
pos.line = 46;
var id35 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"account","id"])));
var exp37 = id35;
var id36 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp37 = (id35)===(id36);
buffer = ifCommand.call(tpl, scope, {params:[exp37],fn: func29}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 56;
var exp39 = 'readStory/';
var id38 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp39 = ('readStory/')+(id38);
var callRet40
callRet40 = callFnUtil(tpl, scope, {escape:1,params:[exp39]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet40);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 57;
var id41 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id41);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 59;
var id42 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"account","name"])));
buffer = buffer.writeEscaped(id42);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func51(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 77;
var id52 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
buffer = buffer.writeEscaped(id52);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 78;
var id53 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
buffer = buffer.writeEscaped(id53);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 79;
var exp55 = 'editStory/';
var id54 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp55 = ('editStory/')+(id54);
var callRet56
callRet56 = callFnUtil(tpl, scope, {escape:1,params:[exp55]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet56);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func44(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 67;
var exp46 = 'readStory/';
var id45 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp46 = ('readStory/')+(id45);
var callRet47
callRet47 = callFnUtil(tpl, scope, {escape:1,params:[exp46]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet47);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 69;
var id48 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"title"])));
buffer = buffer.writeEscaped(id48);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 73;
var id49 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"createTime"])));
buffer = buffer.writeEscaped(id49);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 74;
var id50 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"editTime"])));
buffer = buffer.writeEscaped(id50);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 76;
pos.line = 76;
var id57 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"account","id"])));
var exp59 = id57;
var id58 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp59 = (id57)===(id58);
buffer = ifCommand.call(tpl, scope, {params:[exp59],fn: func51}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 86;
var exp61 = 'readStory/';
var id60 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp61 = ('readStory/')+(id60);
var callRet62
callRet62 = callFnUtil(tpl, scope, {escape:1,params:[exp61]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet62);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 87;
var id63 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id63);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 89;
var id64 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"account","name"])));
buffer = buffer.writeEscaped(id64);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func73(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 107;
var id74 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
buffer = buffer.writeEscaped(id74);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 108;
var id75 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
buffer = buffer.writeEscaped(id75);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 109;
var exp77 = 'editStory/';
var id76 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp77 = ('editStory/')+(id76);
var callRet78
callRet78 = callFnUtil(tpl, scope, {escape:1,params:[exp77]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet78);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func66(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 97;
var exp68 = 'readStory/';
var id67 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp68 = ('readStory/')+(id67);
var callRet69
callRet69 = callFnUtil(tpl, scope, {escape:1,params:[exp68]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet69);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 99;
var id70 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"title"])));
buffer = buffer.writeEscaped(id70);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 103;
var id71 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"createTime"])));
buffer = buffer.writeEscaped(id71);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 104;
var id72 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"editTime"])));
buffer = buffer.writeEscaped(id72);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 106;
pos.line = 106;
var id79 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"account","id"])));
var exp81 = id79;
var id80 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp81 = (id79)===(id80);
buffer = ifCommand.call(tpl, scope, {params:[exp81],fn: func73}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 116;
var exp83 = 'readStory/';
var id82 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp83 = ('readStory/')+(id82);
var callRet84
callRet84 = callFnUtil(tpl, scope, {escape:1,params:[exp83]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet84);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 117;
var id85 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id85);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 119;
var id86 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"account","name"])));
buffer = buffer.writeEscaped(id86);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func95(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 137;
var id96 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
buffer = buffer.writeEscaped(id96);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 138;
var id97 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
buffer = buffer.writeEscaped(id97);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 139;
var exp99 = 'editStory/';
var id98 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp99 = ('editStory/')+(id98);
var callRet100
callRet100 = callFnUtil(tpl, scope, {escape:1,params:[exp99]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet100);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func88(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 127;
var exp90 = 'readStory/';
var id89 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp90 = ('readStory/')+(id89);
var callRet91
callRet91 = callFnUtil(tpl, scope, {escape:1,params:[exp90]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet91);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 129;
var id92 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"title"])));
buffer = buffer.writeEscaped(id92);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 133;
var id93 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"createTime"])));
buffer = buffer.writeEscaped(id93);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 134;
var id94 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"editTime"])));
buffer = buffer.writeEscaped(id94);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 136;
pos.line = 136;
var id101 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"account","id"])));
var exp103 = id101;
var id102 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp103 = (id101)===(id102);
buffer = ifCommand.call(tpl, scope, {params:[exp103],fn: func95}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 146;
var exp105 = 'readStory/';
var id104 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp105 = ('readStory/')+(id104);
var callRet106
callRet106 = callFnUtil(tpl, scope, {escape:1,params:[exp105]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet106);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 147;
var id107 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id107);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 149;
var id108 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"account","name"])));
buffer = buffer.writeEscaped(id108);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func117(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 167;
var id118 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
buffer = buffer.writeEscaped(id118);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 168;
var id119 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
buffer = buffer.writeEscaped(id119);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 169;
var exp121 = 'editStory/';
var id120 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp121 = ('editStory/')+(id120);
var callRet122
callRet122 = callFnUtil(tpl, scope, {escape:1,params:[exp121]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet122);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func110(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 157;
var exp112 = 'readStory/';
var id111 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp112 = ('readStory/')+(id111);
var callRet113
callRet113 = callFnUtil(tpl, scope, {escape:1,params:[exp112]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet113);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 159;
var id114 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"title"])));
buffer = buffer.writeEscaped(id114);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 163;
var id115 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"createTime"])));
buffer = buffer.writeEscaped(id115);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 164;
var id116 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"editTime"])));
buffer = buffer.writeEscaped(id116);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 166;
pos.line = 166;
var id123 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"account","id"])));
var exp125 = id123;
var id124 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp125 = (id123)===(id124);
buffer = ifCommand.call(tpl, scope, {params:[exp125],fn: func117}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 176;
var exp127 = 'readStory/';
var id126 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp127 = ('readStory/')+(id126);
var callRet128
callRet128 = callFnUtil(tpl, scope, {escape:1,params:[exp127]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet128);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 177;
var id129 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id129);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 179;
var id130 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"account","name"])));
buffer = buffer.writeEscaped(id130);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func139(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 197;
var id140 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
buffer = buffer.writeEscaped(id140);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 198;
var id141 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
buffer = buffer.writeEscaped(id141);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 199;
var exp143 = 'editStory/';
var id142 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp143 = ('editStory/')+(id142);
var callRet144
callRet144 = callFnUtil(tpl, scope, {escape:1,params:[exp143]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet144);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func132(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 187;
var exp134 = 'readStory/';
var id133 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp134 = ('readStory/')+(id133);
var callRet135
callRet135 = callFnUtil(tpl, scope, {escape:1,params:[exp134]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet135);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 189;
var id136 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"title"])));
buffer = buffer.writeEscaped(id136);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 193;
var id137 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"createTime"])));
buffer = buffer.writeEscaped(id137);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 194;
var id138 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"editTime"])));
buffer = buffer.writeEscaped(id138);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 196;
pos.line = 196;
var id145 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"account","id"])));
var exp147 = id145;
var id146 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp147 = (id145)===(id146);
buffer = ifCommand.call(tpl, scope, {params:[exp147],fn: func139}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 206;
var exp149 = 'readStory/';
var id148 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp149 = ('readStory/')+(id148);
var callRet150
callRet150 = callFnUtil(tpl, scope, {escape:1,params:[exp149]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet150);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 207;
var id151 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id151);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 209;
var id152 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"account","name"])));
buffer = buffer.writeEscaped(id152);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func161(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 227;
var id162 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
buffer = buffer.writeEscaped(id162);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 228;
var id163 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
buffer = buffer.writeEscaped(id163);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 229;
var exp165 = 'editStory/';
var id164 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp165 = ('editStory/')+(id164);
var callRet166
callRet166 = callFnUtil(tpl, scope, {escape:1,params:[exp165]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet166);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func154(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 217;
var exp156 = 'readStory/';
var id155 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp156 = ('readStory/')+(id155);
var callRet157
callRet157 = callFnUtil(tpl, scope, {escape:1,params:[exp156]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet157);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 219;
var id158 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"title"])));
buffer = buffer.writeEscaped(id158);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 223;
var id159 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"createTime"])));
buffer = buffer.writeEscaped(id159);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 224;
var id160 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"editTime"])));
buffer = buffer.writeEscaped(id160);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 226;
pos.line = 226;
var id167 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"account","id"])));
var exp169 = id167;
var id168 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp169 = (id167)===(id168);
buffer = ifCommand.call(tpl, scope, {params:[exp169],fn: func161}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 236;
var exp171 = 'readStory/';
var id170 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp171 = ('readStory/')+(id170);
var callRet172
callRet172 = callFnUtil(tpl, scope, {escape:1,params:[exp171]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet172);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 237;
var id173 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id173);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 239;
var id174 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"account","name"])));
buffer = buffer.writeEscaped(id174);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func183(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 257;
var id184 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
buffer = buffer.writeEscaped(id184);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 258;
var id185 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
buffer = buffer.writeEscaped(id185);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 259;
var exp187 = 'editStory/';
var id186 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp187 = ('editStory/')+(id186);
var callRet188
callRet188 = callFnUtil(tpl, scope, {escape:1,params:[exp187]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet188);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func176(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 247;
var exp178 = 'readStory/';
var id177 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp178 = ('readStory/')+(id177);
var callRet179
callRet179 = callFnUtil(tpl, scope, {escape:1,params:[exp178]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet179);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 249;
var id180 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"title"])));
buffer = buffer.writeEscaped(id180);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 253;
var id181 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"createTime"])));
buffer = buffer.writeEscaped(id181);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 254;
var id182 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"editTime"])));
buffer = buffer.writeEscaped(id182);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 256;
pos.line = 256;
var id189 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"account","id"])));
var exp191 = id189;
var id190 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp191 = (id189)===(id190);
buffer = ifCommand.call(tpl, scope, {params:[exp191],fn: func183}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 266;
var exp193 = 'readStory/';
var id192 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp193 = ('readStory/')+(id192);
var callRet194
callRet194 = callFnUtil(tpl, scope, {escape:1,params:[exp193]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet194);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 267;
var id195 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id195);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 269;
var id196 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"account","name"])));
buffer = buffer.writeEscaped(id196);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}
function func205(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 287;
var id206 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
buffer = buffer.writeEscaped(id206);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 288;
var id207 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
buffer = buffer.writeEscaped(id207);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 289;
var exp209 = 'editStory/';
var id208 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp209 = ('editStory/')+(id208);
var callRet210
callRet210 = callFnUtil(tpl, scope, {escape:1,params:[exp209]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet210);
buffer.data += '"\n                               target="_blank"></a>\n                            ';
return buffer;
}
function func198(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 277;
var exp200 = 'readStory/';
var id199 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp200 = ('readStory/')+(id199);
var callRet201
callRet201 = callFnUtil(tpl, scope, {escape:1,params:[exp200]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet201);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 279;
var id202 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"title"])));
buffer = buffer.writeEscaped(id202);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 283;
var id203 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"createTime"])));
buffer = buffer.writeEscaped(id203);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 284;
var id204 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"editTime"])));
buffer = buffer.writeEscaped(id204);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 286;
pos.line = 286;
var id211 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"account","id"])));
var exp213 = id211;
var id212 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp213 = (id211)===(id212);
buffer = ifCommand.call(tpl, scope, {params:[exp213],fn: func205}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 296;
var exp215 = 'readStory/';
var id214 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp215 = ('readStory/')+(id214);
var callRet216
callRet216 = callFnUtil(tpl, scope, {escape:1,params:[exp215]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet216);
buffer.data += '" target="_blank" class="item-link">\n                <span class="name"><img src="';
pos.line = 297;
var id217 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].account.accountBucket[0].smallPortrait:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?((t2=t1.account) != null?((t3=t2.accountBucket) != null?((t4=t3[0]) != null?(t4.smallPortrait):t4):t3):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"account","accountBucket",0,"smallPortrait"])));
buffer = buffer.writeEscaped(id217);
buffer.data += '"\n                                        class="smallPortrait">\n                    <span class="smallPortrait-name">';
pos.line = 299;
var id218 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"account","name"])));
buffer = buffer.writeEscaped(id218);
buffer.data += '</span>\n                </span>\n            </a>\n            ';
return buffer;
}


buffer.data += '<p>\n<div class="component kissy-ui" style="margin-left: 5px">\n    <ul id="J_KISSYUI" class="component-list" style="width: 920px">\n        <li class="item">\n            ';
pos.line = 5;
pos.line = 5;
var id21 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[0]):t0) :scope.resolveLooseUp(["p","pageItems",0])));
buffer = ifCommand.call(tpl, scope, {params:[id21],fn: func0}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 35;
pos.line = 35;
var id43 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[1]):t0) :scope.resolveLooseUp(["p","pageItems",1])));
buffer = ifCommand.call(tpl, scope, {params:[id43],fn: func22}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 65;
pos.line = 65;
var id65 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[2]):t0) :scope.resolveLooseUp(["p","pageItems",2])));
buffer = ifCommand.call(tpl, scope, {params:[id65],fn: func44}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 95;
pos.line = 95;
var id87 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[3]):t0) :scope.resolveLooseUp(["p","pageItems",3])));
buffer = ifCommand.call(tpl, scope, {params:[id87],fn: func66}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 125;
pos.line = 125;
var id109 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[4]):t0) :scope.resolveLooseUp(["p","pageItems",4])));
buffer = ifCommand.call(tpl, scope, {params:[id109],fn: func88}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 155;
pos.line = 155;
var id131 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[5]):t0) :scope.resolveLooseUp(["p","pageItems",5])));
buffer = ifCommand.call(tpl, scope, {params:[id131],fn: func110}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 185;
pos.line = 185;
var id153 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[6]):t0) :scope.resolveLooseUp(["p","pageItems",6])));
buffer = ifCommand.call(tpl, scope, {params:[id153],fn: func132}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 215;
pos.line = 215;
var id175 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[7]):t0) :scope.resolveLooseUp(["p","pageItems",7])));
buffer = ifCommand.call(tpl, scope, {params:[id175],fn: func154}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 245;
pos.line = 245;
var id197 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[8]):t0) :scope.resolveLooseUp(["p","pageItems",8])));
buffer = ifCommand.call(tpl, scope, {params:[id197],fn: func176}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 275;
pos.line = 275;
var id219 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[9]):t0) :scope.resolveLooseUp(["p","pageItems",9])));
buffer = ifCommand.call(tpl, scope, {params:[id219],fn: func198}, buffer);
buffer.data += '\n        </li>\n    </ul>\n</div>\n</p>';
return buffer;
};
ret.TPL_NAME = module.id || module.name;
});