KISSY.add(function(S,require,exports,module){
/*compiled by xtemplate#3.3.3*/
var ret = module.exports = function homeView(undefined){
var t;
var t0;
var t1;
var t2;
var t3;
var t4;
var t5;
var t6;
var t7;
var t8;
var t9;
var tpl = this;
var root = tpl.root;
var buffer = tpl.buffer;
var scope = tpl.scope;
var runtime = tpl.runtime;
var name = tpl.name;
var pos = tpl.pos;
var data = scope.data;
var affix = scope.affix;
var nativeCommands = root.nativeCommands;
var utils = root.utils;
var callFnUtil = utils["callFn"];
var callCommandUtil = utils["callCommand"];
var rangeCommand = nativeCommands["range"];
var foreachCommand = nativeCommands["foreach"];
var forinCommand = nativeCommands["forin"];
var eachCommand = nativeCommands["each"];
var withCommand = nativeCommands["with"];
var ifCommand = nativeCommands["if"];
var setCommand = nativeCommands["set"];
var includeCommand = nativeCommands["include"];
var parseCommand = nativeCommands["parse"];
var extendCommand = nativeCommands["extend"];
var blockCommand = nativeCommands["block"];
var macroCommand = nativeCommands["macro"];
var debuggerCommand = nativeCommands["debugger"];
function func7(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 17;
var id8 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
buffer = buffer.writeEscaped(id8);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 18;
var id9 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
buffer = buffer.writeEscaped(id9);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 19;
var exp11 = 'editStory/';
var id10 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp11 = ('editStory/')+(id10);
var callRet12
callRet12 = callFnUtil(tpl, scope, {escape:1,params:[exp11]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet12);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func0(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 7;
var exp2 = 'readStory/';
var id1 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp2 = ('readStory/')+(id1);
var callRet3
callRet3 = callFnUtil(tpl, scope, {escape:1,params:[exp2]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet3);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 9;
var id4 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"title"])));
buffer = buffer.writeEscaped(id4);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 13;
var id5 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"createTime"])));
buffer = buffer.writeEscaped(id5);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 14;
var id6 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"editTime"])));
buffer = buffer.writeEscaped(id6);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 16;
pos.line = 16;
var id13 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"account","id"])));
var exp15 = id13;
var id14 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp15 = (id13)===(id14);
buffer = ifCommand.call(tpl, scope, {params:[exp15],fn: func7}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 25;
var exp17 = 'readStory/';
var id16 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"id"])));
exp17 = ('readStory/')+(id16);
var callRet18
callRet18 = callFnUtil(tpl, scope, {escape:1,params:[exp17]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet18);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 26;
var id19 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[0]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",0,"account","name"])));
buffer = buffer.writeEscaped(id19);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func28(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 43;
var id29 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
buffer = buffer.writeEscaped(id29);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 44;
var id30 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
buffer = buffer.writeEscaped(id30);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 45;
var exp32 = 'editStory/';
var id31 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp32 = ('editStory/')+(id31);
var callRet33
callRet33 = callFnUtil(tpl, scope, {escape:1,params:[exp32]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet33);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func21(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 33;
var exp23 = 'readStory/';
var id22 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp23 = ('readStory/')+(id22);
var callRet24
callRet24 = callFnUtil(tpl, scope, {escape:1,params:[exp23]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet24);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 35;
var id25 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"title"])));
buffer = buffer.writeEscaped(id25);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 39;
var id26 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"createTime"])));
buffer = buffer.writeEscaped(id26);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 40;
var id27 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"editTime"])));
buffer = buffer.writeEscaped(id27);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 42;
pos.line = 42;
var id34 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"account","id"])));
var exp36 = id34;
var id35 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp36 = (id34)===(id35);
buffer = ifCommand.call(tpl, scope, {params:[exp36],fn: func28}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 51;
var exp38 = 'readStory/';
var id37 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"id"])));
exp38 = ('readStory/')+(id37);
var callRet39
callRet39 = callFnUtil(tpl, scope, {escape:1,params:[exp38]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet39);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 52;
var id40 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[1]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",1,"account","name"])));
buffer = buffer.writeEscaped(id40);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func49(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 69;
var id50 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
buffer = buffer.writeEscaped(id50);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 70;
var id51 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
buffer = buffer.writeEscaped(id51);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 71;
var exp53 = 'editStory/';
var id52 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp53 = ('editStory/')+(id52);
var callRet54
callRet54 = callFnUtil(tpl, scope, {escape:1,params:[exp53]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet54);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func42(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 59;
var exp44 = 'readStory/';
var id43 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp44 = ('readStory/')+(id43);
var callRet45
callRet45 = callFnUtil(tpl, scope, {escape:1,params:[exp44]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet45);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 61;
var id46 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"title"])));
buffer = buffer.writeEscaped(id46);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 65;
var id47 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"createTime"])));
buffer = buffer.writeEscaped(id47);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 66;
var id48 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"editTime"])));
buffer = buffer.writeEscaped(id48);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 68;
pos.line = 68;
var id55 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"account","id"])));
var exp57 = id55;
var id56 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp57 = (id55)===(id56);
buffer = ifCommand.call(tpl, scope, {params:[exp57],fn: func49}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 77;
var exp59 = 'readStory/';
var id58 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"id"])));
exp59 = ('readStory/')+(id58);
var callRet60
callRet60 = callFnUtil(tpl, scope, {escape:1,params:[exp59]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet60);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 78;
var id61 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[2]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",2,"account","name"])));
buffer = buffer.writeEscaped(id61);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func70(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 95;
var id71 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
buffer = buffer.writeEscaped(id71);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 96;
var id72 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
buffer = buffer.writeEscaped(id72);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 97;
var exp74 = 'editStory/';
var id73 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp74 = ('editStory/')+(id73);
var callRet75
callRet75 = callFnUtil(tpl, scope, {escape:1,params:[exp74]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet75);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func63(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 85;
var exp65 = 'readStory/';
var id64 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp65 = ('readStory/')+(id64);
var callRet66
callRet66 = callFnUtil(tpl, scope, {escape:1,params:[exp65]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet66);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 87;
var id67 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"title"])));
buffer = buffer.writeEscaped(id67);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 91;
var id68 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"createTime"])));
buffer = buffer.writeEscaped(id68);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 92;
var id69 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"editTime"])));
buffer = buffer.writeEscaped(id69);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 94;
pos.line = 94;
var id76 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"account","id"])));
var exp78 = id76;
var id77 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp78 = (id76)===(id77);
buffer = ifCommand.call(tpl, scope, {params:[exp78],fn: func70}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 103;
var exp80 = 'readStory/';
var id79 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"id"])));
exp80 = ('readStory/')+(id79);
var callRet81
callRet81 = callFnUtil(tpl, scope, {escape:1,params:[exp80]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet81);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 104;
var id82 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[3]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",3,"account","name"])));
buffer = buffer.writeEscaped(id82);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func91(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 121;
var id92 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
buffer = buffer.writeEscaped(id92);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 122;
var id93 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
buffer = buffer.writeEscaped(id93);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 123;
var exp95 = 'editStory/';
var id94 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp95 = ('editStory/')+(id94);
var callRet96
callRet96 = callFnUtil(tpl, scope, {escape:1,params:[exp95]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet96);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func84(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 111;
var exp86 = 'readStory/';
var id85 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp86 = ('readStory/')+(id85);
var callRet87
callRet87 = callFnUtil(tpl, scope, {escape:1,params:[exp86]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet87);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 113;
var id88 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"title"])));
buffer = buffer.writeEscaped(id88);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 117;
var id89 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"createTime"])));
buffer = buffer.writeEscaped(id89);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 118;
var id90 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"editTime"])));
buffer = buffer.writeEscaped(id90);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 120;
pos.line = 120;
var id97 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"account","id"])));
var exp99 = id97;
var id98 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp99 = (id97)===(id98);
buffer = ifCommand.call(tpl, scope, {params:[exp99],fn: func91}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 129;
var exp101 = 'readStory/';
var id100 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"id"])));
exp101 = ('readStory/')+(id100);
var callRet102
callRet102 = callFnUtil(tpl, scope, {escape:1,params:[exp101]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet102);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 130;
var id103 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[4]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",4,"account","name"])));
buffer = buffer.writeEscaped(id103);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func112(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 147;
var id113 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
buffer = buffer.writeEscaped(id113);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 148;
var id114 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
buffer = buffer.writeEscaped(id114);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 149;
var exp116 = 'editStory/';
var id115 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp116 = ('editStory/')+(id115);
var callRet117
callRet117 = callFnUtil(tpl, scope, {escape:1,params:[exp116]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet117);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func105(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 137;
var exp107 = 'readStory/';
var id106 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp107 = ('readStory/')+(id106);
var callRet108
callRet108 = callFnUtil(tpl, scope, {escape:1,params:[exp107]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet108);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 139;
var id109 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"title"])));
buffer = buffer.writeEscaped(id109);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 143;
var id110 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"createTime"])));
buffer = buffer.writeEscaped(id110);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 144;
var id111 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"editTime"])));
buffer = buffer.writeEscaped(id111);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 146;
pos.line = 146;
var id118 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"account","id"])));
var exp120 = id118;
var id119 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp120 = (id118)===(id119);
buffer = ifCommand.call(tpl, scope, {params:[exp120],fn: func112}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 155;
var exp122 = 'readStory/';
var id121 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"id"])));
exp122 = ('readStory/')+(id121);
var callRet123
callRet123 = callFnUtil(tpl, scope, {escape:1,params:[exp122]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet123);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 156;
var id124 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[5]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",5,"account","name"])));
buffer = buffer.writeEscaped(id124);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func133(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 173;
var id134 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
buffer = buffer.writeEscaped(id134);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 174;
var id135 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
buffer = buffer.writeEscaped(id135);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 175;
var exp137 = 'editStory/';
var id136 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp137 = ('editStory/')+(id136);
var callRet138
callRet138 = callFnUtil(tpl, scope, {escape:1,params:[exp137]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet138);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func126(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 163;
var exp128 = 'readStory/';
var id127 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp128 = ('readStory/')+(id127);
var callRet129
callRet129 = callFnUtil(tpl, scope, {escape:1,params:[exp128]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet129);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 165;
var id130 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"title"])));
buffer = buffer.writeEscaped(id130);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 169;
var id131 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"createTime"])));
buffer = buffer.writeEscaped(id131);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 170;
var id132 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"editTime"])));
buffer = buffer.writeEscaped(id132);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 172;
pos.line = 172;
var id139 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"account","id"])));
var exp141 = id139;
var id140 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp141 = (id139)===(id140);
buffer = ifCommand.call(tpl, scope, {params:[exp141],fn: func133}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 181;
var exp143 = 'readStory/';
var id142 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"id"])));
exp143 = ('readStory/')+(id142);
var callRet144
callRet144 = callFnUtil(tpl, scope, {escape:1,params:[exp143]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet144);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 182;
var id145 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[6]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",6,"account","name"])));
buffer = buffer.writeEscaped(id145);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func154(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 199;
var id155 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
buffer = buffer.writeEscaped(id155);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 200;
var id156 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
buffer = buffer.writeEscaped(id156);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 201;
var exp158 = 'editStory/';
var id157 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp158 = ('editStory/')+(id157);
var callRet159
callRet159 = callFnUtil(tpl, scope, {escape:1,params:[exp158]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet159);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func147(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 189;
var exp149 = 'readStory/';
var id148 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp149 = ('readStory/')+(id148);
var callRet150
callRet150 = callFnUtil(tpl, scope, {escape:1,params:[exp149]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet150);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 191;
var id151 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"title"])));
buffer = buffer.writeEscaped(id151);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 195;
var id152 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"createTime"])));
buffer = buffer.writeEscaped(id152);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 196;
var id153 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"editTime"])));
buffer = buffer.writeEscaped(id153);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 198;
pos.line = 198;
var id160 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"account","id"])));
var exp162 = id160;
var id161 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp162 = (id160)===(id161);
buffer = ifCommand.call(tpl, scope, {params:[exp162],fn: func154}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 207;
var exp164 = 'readStory/';
var id163 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"id"])));
exp164 = ('readStory/')+(id163);
var callRet165
callRet165 = callFnUtil(tpl, scope, {escape:1,params:[exp164]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet165);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 208;
var id166 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[7]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",7,"account","name"])));
buffer = buffer.writeEscaped(id166);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func175(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 225;
var id176 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
buffer = buffer.writeEscaped(id176);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 226;
var id177 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
buffer = buffer.writeEscaped(id177);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 227;
var exp179 = 'editStory/';
var id178 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp179 = ('editStory/')+(id178);
var callRet180
callRet180 = callFnUtil(tpl, scope, {escape:1,params:[exp179]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet180);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func168(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 215;
var exp170 = 'readStory/';
var id169 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp170 = ('readStory/')+(id169);
var callRet171
callRet171 = callFnUtil(tpl, scope, {escape:1,params:[exp170]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet171);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 217;
var id172 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"title"])));
buffer = buffer.writeEscaped(id172);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 221;
var id173 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"createTime"])));
buffer = buffer.writeEscaped(id173);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 222;
var id174 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"editTime"])));
buffer = buffer.writeEscaped(id174);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 224;
pos.line = 224;
var id181 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"account","id"])));
var exp183 = id181;
var id182 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp183 = (id181)===(id182);
buffer = ifCommand.call(tpl, scope, {params:[exp183],fn: func175}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 233;
var exp185 = 'readStory/';
var id184 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"id"])));
exp185 = ('readStory/')+(id184);
var callRet186
callRet186 = callFnUtil(tpl, scope, {escape:1,params:[exp185]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet186);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 234;
var id187 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[8]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",8,"account","name"])));
buffer = buffer.writeEscaped(id187);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}
function func196(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n                            <a class="delete" bind-data="';
pos.line = 251;
var id197 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
buffer = buffer.writeEscaped(id197);
buffer.data += '"></a>\n                            <a class="publish" bind-data="';
pos.line = 252;
var id198 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
buffer = buffer.writeEscaped(id198);
buffer.data += '"></a>\n                            <a class="edit" href="';
pos.line = 253;
var exp200 = 'editStory/';
var id199 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp200 = ('editStory/')+(id199);
var callRet201
callRet201 = callFnUtil(tpl, scope, {escape:1,params:[exp200]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet201);
buffer.data += '" target="_blank"></a>\n                            ';
return buffer;
}
function func189(scope, buffer, undefined) {
var data = scope.data;
var affix = scope.affix;
buffer.data += '\n            <div class="desc">\n                <a href="';
pos.line = 241;
var exp191 = 'readStory/';
var id190 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp191 = ('readStory/')+(id190);
var callRet192
callRet192 = callFnUtil(tpl, scope, {escape:1,params:[exp191]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet192);
buffer.data += '" target="_blank">\n                    <div class="cover">\n                        <div class="coverTitle">';
pos.line = 243;
var id193 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].title:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.title):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"title"])));
buffer = buffer.writeEscaped(id193);
buffer.data += '</div>\n                    </div>\n                    <div class="content">\n                        <div class="writer">作者</div>\n                        <div>创作于：';
pos.line = 247;
var id194 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].createTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.createTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"createTime"])));
buffer = buffer.writeEscaped(id194);
buffer.data += '</div>\n                        <div>更新于：';
pos.line = 248;
var id195 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].editTime:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.editTime):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"editTime"])));
buffer = buffer.writeEscaped(id195);
buffer.data += '</div>\n                        <div class="panel">\n                            ';
pos.line = 250;
pos.line = 250;
var id202 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].account.id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?((t2=t1.account) != null?(t2.id):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"account","id"])));
var exp204 = id202;
var id203 = ((t=(affix.account)) !== undefined ? affix.account.id:((t = data.account) !== undefined ? (t.id) :scope.resolveLooseUp(["account","id"])));
exp204 = (id202)===(id203);
buffer = ifCommand.call(tpl, scope, {params:[exp204],fn: func196}, buffer);
buffer.data += '\n                        </div>\n                    </div>\n                </a>\n            </div>\n            <a href="';
pos.line = 259;
var exp206 = 'readStory/';
var id205 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].id:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?(t1.id):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"id"])));
exp206 = ('readStory/')+(id205);
var callRet207
callRet207 = callFnUtil(tpl, scope, {escape:1,params:[exp206]}, buffer, ["SP","resolvedPath"]);
buffer = buffer.writeEscaped(callRet207);
buffer.data += '" target="_blank" class="item-link">\n                <h4 class="name l-block">';
pos.line = 260;
var id208 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9].account.name:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?((t1=t0[9]) != null?((t2=t1.account) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["p","pageItems",9,"account","name"])));
buffer = buffer.writeEscaped(id208);
buffer.data += '</h4>\n            </a>\n            ';
return buffer;
}


buffer.data += '<p>\n<div class="component kissy-ui" style="margin-left: 5px">\n    <ul id="J_KISSYUI" class="component-list" style="width: 920px">\n        <li class="item">\n            ';
pos.line = 5;
pos.line = 5;
var id20 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[0]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[0]):t0) :scope.resolveLooseUp(["p","pageItems",0])));
buffer = ifCommand.call(tpl, scope, {params:[id20],fn: func0}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 31;
pos.line = 31;
var id41 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[1]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[1]):t0) :scope.resolveLooseUp(["p","pageItems",1])));
buffer = ifCommand.call(tpl, scope, {params:[id41],fn: func21}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 57;
pos.line = 57;
var id62 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[2]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[2]):t0) :scope.resolveLooseUp(["p","pageItems",2])));
buffer = ifCommand.call(tpl, scope, {params:[id62],fn: func42}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 83;
pos.line = 83;
var id83 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[3]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[3]):t0) :scope.resolveLooseUp(["p","pageItems",3])));
buffer = ifCommand.call(tpl, scope, {params:[id83],fn: func63}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 109;
pos.line = 109;
var id104 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[4]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[4]):t0) :scope.resolveLooseUp(["p","pageItems",4])));
buffer = ifCommand.call(tpl, scope, {params:[id104],fn: func84}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 135;
pos.line = 135;
var id125 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[5]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[5]):t0) :scope.resolveLooseUp(["p","pageItems",5])));
buffer = ifCommand.call(tpl, scope, {params:[id125],fn: func105}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 161;
pos.line = 161;
var id146 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[6]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[6]):t0) :scope.resolveLooseUp(["p","pageItems",6])));
buffer = ifCommand.call(tpl, scope, {params:[id146],fn: func126}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 187;
pos.line = 187;
var id167 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[7]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[7]):t0) :scope.resolveLooseUp(["p","pageItems",7])));
buffer = ifCommand.call(tpl, scope, {params:[id167],fn: func147}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 213;
pos.line = 213;
var id188 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[8]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[8]):t0) :scope.resolveLooseUp(["p","pageItems",8])));
buffer = ifCommand.call(tpl, scope, {params:[id188],fn: func168}, buffer);
buffer.data += '\n        </li>\n        <li class="item">\n            ';
pos.line = 239;
pos.line = 239;
var id209 = ((t=(affix.p)) !== undefined ? affix.p.pageItems[9]:((t = data.p) !== undefined ? ((t0=t.pageItems) != null?(t0[9]):t0) :scope.resolveLooseUp(["p","pageItems",9])));
buffer = ifCommand.call(tpl, scope, {params:[id209],fn: func189}, buffer);
buffer.data += '\n        </li>\n    </ul>\n</div>\n</p>';
return buffer;
};
ret.TPL_NAME = module.id || module.name;
});